apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  labels:
    app: hello-k8s
  annotations:
    service-info: "Service exposing the hello-k8s deployment"
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30080
    # type: LoadBalancer

